# Generated by Django 4.1 on 2022-10-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(default='ref_token_default_val', help_text='Refresh token is used to retrieve new ID tokens for Firebase auth. It is expires only if the user is disabed, deleted or has major account change'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='uid_default_val', help_text='Unique value that user gets from firebase after registration', max_length=150, unique=True),
        ),
    ]
